CREATE TABLE public.exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  category text NOT NULL DEFAULT 'strength',
  muscle_groups text[] NOT NULL DEFAULT '{}',
  equipment text[] NOT NULL DEFAULT '{}',
  difficulty text NOT NULL DEFAULT 'beginner',
  setting text NOT NULL DEFAULT 'home',
  sports text[] NOT NULL DEFAULT '{}',
  default_sets integer,
  default_reps text,
  duration_sec integer,
  rest_sec integer,
  instructions text[] NOT NULL DEFAULT '{}',
  safety_cues text[] NOT NULL DEFAULT '{}',
  contraindications text[] NOT NULL DEFAULT '{}',
  alternatives text[] NOT NULL DEFAULT '{}',
  progressions text[] NOT NULL DEFAULT '{}',
  regressions text[] NOT NULL DEFAULT '{}',
  video_url text,
  min_age integer,
  data_source text NOT NULL DEFAULT 'Unverified',
  source_url text,
  confidence text NOT NULL DEFAULT 'medium',
  verified boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.exercises TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercises TO authenticated;
GRANT ALL ON public.exercises TO service_role;

ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read exercises" ON public.exercises FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Users can add exercises" ON public.exercises FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Users can edit own exercises" ON public.exercises FOR UPDATE TO authenticated USING (auth.uid() = created_by) WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Users can delete own exercises" ON public.exercises FOR DELETE TO authenticated USING (auth.uid() = created_by);

CREATE TRIGGER update_exercises_updated_at BEFORE UPDATE ON public.exercises
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX exercises_category_idx ON public.exercises (category);
CREATE INDEX exercises_name_idx ON public.exercises (lower(name));

CREATE TABLE public.training_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL DEFAULT 'Training plan',
  goal text,
  focus text[] NOT NULL DEFAULT '{}',
  fitness_level text,
  age_range text,
  equipment text[] NOT NULL DEFAULT '{}',
  sport text,
  days_per_week integer NOT NULL DEFAULT 3,
  session_minutes integer NOT NULL DEFAULT 45,
  week jsonb NOT NULL DEFAULT '[]'::jsonb,
  rationale text,
  safety_notes text[] NOT NULL DEFAULT '{}',
  adjustments jsonb NOT NULL DEFAULT '[]'::jsonb,
  inputs_signature text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.training_plans TO authenticated;
GRANT ALL ON public.training_plans TO service_role;

ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own training plans" ON public.training_plans FOR ALL TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER update_training_plans_updated_at BEFORE UPDATE ON public.training_plans
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.workouts
  ADD COLUMN IF NOT EXISTS perceived_effort integer,
  ADD COLUMN IF NOT EXISTS exercises jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS rest_day boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS plan_id uuid;

INSERT INTO public.exercises (name, slug, category, muscle_groups, equipment, difficulty, setting, sports, default_sets, default_reps, duration_sec, rest_sec, instructions, safety_cues, contraindications, alternatives, progressions, regressions, min_age, data_source, source_url, confidence, verified) VALUES
('Bodyweight squat','bodyweight-squat','strength','{quadriceps,glutes,core}','{none}','beginner','home','{}',3,'10-15',NULL,60,'{"Stand with feet shoulder-width apart, toes slightly out.","Push hips back and bend knees, keeping chest tall.","Lower until thighs are near parallel or as far as comfortable.","Drive through mid-foot to stand, squeezing glutes at the top."}','{"Keep knees tracking over toes, not caving inward.","Stop at the depth where your lower back stays neutral.","Breathe in on the way down, out on the way up."}','{"Acute knee or hip injury","Recent lower-limb surgery without clearance"}','{"Box squat","Wall sit","Split squat"}','{"Tempo squat (3s down)","Jump squat","Goblet squat"}','{"Box squat to a chair","Partial-range squat"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Push-up','push-up','strength','{chest,triceps,shoulders,core}','{none}','beginner','home','{}',3,'6-15',NULL,60,'{"Set hands slightly wider than shoulders, body in one line.","Brace your core and glutes.","Lower chest toward the floor with elbows about 45° from your body.","Press back to the start without letting hips sag."}','{"Do not flare elbows to 90°.","Keep neck neutral, eyes just ahead of your hands.","Reduce range before letting form break down."}','{"Acute shoulder, elbow or wrist pain"}','{"Incline push-up","Knee push-up","Dumbbell bench press"}','{"Feet-elevated push-up","Tempo push-up","Archer push-up"}','{"Wall push-up","Incline push-up on a bench"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Incline push-up','incline-push-up','strength','{chest,triceps,shoulders}','{bench}','beginner','home','{}',3,'8-15',NULL,60,'{"Place hands on a stable bench, table or wall.","Walk feet back so your body forms a straight line.","Lower chest to the surface under control.","Press back up."}','{"The higher the surface, the easier the exercise.","Keep hips level with shoulders."}','{"Acute shoulder or wrist pain"}','{"Knee push-up","Wall push-up"}','{"Lower the surface","Standard push-up"}','{"Wall push-up"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Glute bridge','glute-bridge','strength','{glutes,hamstrings,core}','{none}','beginner','home','{}',3,'12-20',NULL,45,'{"Lie on your back, knees bent, feet flat and hip-width apart.","Press through your heels and lift hips until shoulders, hips and knees line up.","Pause for one second and squeeze your glutes.","Lower with control."}','{"Do not over-arch the lower back at the top.","Ribs stay down, core braced."}','{"Acute lower-back pain that worsens with extension"}','{"Hip thrust","Single-leg glute bridge"}','{"Single-leg glute bridge","Barbell hip thrust"}','{"Shorter range of motion"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Plank','plank','stability','{core,shoulders,glutes}','{none}','beginner','home','{}',3,NULL,30,45,'{"Set forearms under shoulders, feet hip-width apart.","Brace your core and squeeze glutes so your body is one straight line.","Breathe steadily and hold."}','{"Stop the set when hips start to sag or pike — quality over duration.","Do not hold your breath."}','{"Late pregnancy","Acute lower-back pain"}','{"Knee plank","Dead bug","Bird dog"}','{"Long-lever plank","Plank with shoulder taps"}','{"Knee plank","Incline plank on a bench"}',NULL,'ACSM core training guidance','https://www.acsm.org','high',true),
('Dead bug','dead-bug','stability','{core,hip flexors}','{none}','beginner','home','{}',3,'8-10 each side',NULL,45,'{"Lie on your back, arms straight up, hips and knees at 90°.","Press your lower back gently into the floor.","Slowly lower one arm and the opposite leg.","Return and switch sides."}','{"Only go as far as you can without the lower back lifting.","Move slowly — this is a control drill, not a speed drill."}','{}','{"Bird dog","Plank"}','{"Straight-leg dead bug","Add a light weight"}','{"Heels-only dead bug"}',NULL,'NSCA core stability guidance','https://www.nsca.com','high',true),
('Bird dog','bird-dog','stability','{core,glutes,back}','{none}','beginner','home','{}',3,'8-10 each side',NULL,45,'{"Start on hands and knees, spine neutral.","Extend one arm forward and the opposite leg back.","Hold 2 seconds without rotating the hips.","Return and switch."}','{"Keep hips square to the floor.","Do not arch the lower back to gain reach."}','{}','{"Dead bug","Plank"}','{"Add a pause or a resistance band"}','{"Leg-only or arm-only version"}',NULL,'NSCA core stability guidance','https://www.nsca.com','high',true),
('Walking lunge','walking-lunge','strength','{quadriceps,glutes,hamstrings}','{none}','intermediate','home','{}',3,'8-12 each leg',NULL,60,'{"Step forward into a lunge, both knees bending to about 90°.","Keep torso tall and core braced.","Drive through the front heel to bring the back leg through.","Continue alternating."}','{"Front knee stays over the middle of the foot.","Take a shorter step if balance is unsteady."}','{"Acute knee pain","Balance impairment without support"}','{"Split squat","Reverse lunge","Step-up"}','{"Add dumbbells","Deficit lunge"}','{"Static split squat holding a wall"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Reverse lunge','reverse-lunge','strength','{quadriceps,glutes,hamstrings}','{none}','beginner','home','{}',3,'8-12 each leg',NULL,60,'{"Step one foot back and lower the back knee toward the floor.","Keep the front shin close to vertical.","Push through the front foot to return to standing."}','{"Stepping backwards is usually kinder to the knees than stepping forwards.","Hold a wall for balance if needed."}','{"Acute knee pain"}','{"Split squat","Step-up"}','{"Add dumbbells","Deficit reverse lunge"}','{"Supported split squat"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Goblet squat','goblet-squat','strength','{quadriceps,glutes,core}','{dumbbell,kettlebell}','beginner','gym','{}',3,'8-12',NULL,90,'{"Hold a dumbbell or kettlebell at chest height.","Squat down between your hips, elbows inside the knees.","Keep the chest up and drive back to standing."}','{"Let the weight act as a counterbalance — chest stays tall.","Do not round the lower back at the bottom."}','{"Acute knee or back injury"}','{"Bodyweight squat","Leg press"}','{"Front squat","Barbell back squat"}','{"Bodyweight squat","Box squat"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Barbell back squat','barbell-back-squat','strength','{quadriceps,glutes,hamstrings,core}','{barbell,squat rack}','advanced','gym','{}',4,'5-8',NULL,150,'{"Set the bar on your upper back, hands just outside the shoulders.","Unrack, step back, feet shoulder-width.","Brace, sit down and back to depth you control.","Drive up through mid-foot."}','{"Always use safety pins or a spotter.","Stop the set when depth or bar path breaks down.","Build load gradually — no more than about 5-10% per week."}','{"Uncontrolled hypertension","Acute back or knee injury","Beginners without coaching"}','{"Goblet squat","Leg press","Hack squat"}','{"Increase load gradually","Pause squat"}','{"Goblet squat","Box squat"}',16,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Romanian deadlift','romanian-deadlift','strength','{hamstrings,glutes,back}','{barbell,dumbbell}','intermediate','gym','{}',3,'6-10',NULL,120,'{"Hold the bar at hip height, knees softly bent.","Push hips back and slide the bar down your thighs.","Stop when you feel a hamstring stretch with a flat back.","Drive hips forward to stand."}','{"The spine stays neutral throughout — no rounding.","Range is limited by your hamstrings, not by touching the floor."}','{"Acute lower-back injury","Disc symptoms without clearance"}','{"Hip hinge with a dowel","Cable pull-through","Glute bridge"}','{"Single-leg RDL","Increase load gradually"}','{"Dumbbell RDL with lighter load","Hip hinge drill"}',16,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Deadlift','deadlift','strength','{hamstrings,glutes,back,grip}','{barbell}','advanced','gym','{}',4,'3-6',NULL,180,'{"Stand mid-foot under the bar, grip just outside the knees.","Set your back flat, chest up, lats engaged.","Push the floor away and stand tall.","Return the bar under control along the same path."}','{"Never round the lower back under load.","Leave 1-2 reps in reserve on most sets.","Load progression should stay conservative and gradual."}','{"Acute back injury","Uncontrolled hypertension","Untrained lifters without coaching"}','{"Trap-bar deadlift","Romanian deadlift","Hip thrust"}','{"Add small increments","Deficit deadlift"}','{"Rack pull","Trap-bar deadlift"}',16,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Dumbbell bench press','dumbbell-bench-press','strength','{chest,triceps,shoulders}','{dumbbell,bench}','intermediate','gym','{}',3,'8-12',NULL,90,'{"Lie on a bench with a dumbbell in each hand at chest level.","Press up until the arms are straight, wrists over elbows.","Lower with control to a comfortable stretch."}','{"Keep shoulder blades pulled back and down.","Do not bounce the weights off your chest."}','{"Acute shoulder impingement"}','{"Push-up","Machine chest press"}','{"Increase load","Single-arm press"}','{"Incline push-up","Machine press"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Bent-over row','bent-over-row','strength','{back,biceps,rear delts}','{barbell,dumbbell}','intermediate','gym','{}',3,'8-12',NULL,90,'{"Hinge forward to about 45°, back flat.","Pull the weight to your lower ribs, elbows close.","Lower under control."}','{"Do not jerk with the lower back.","Keep the neck in line with the spine."}','{"Acute lower-back pain"}','{"Seated cable row","Single-arm dumbbell row","Inverted row"}','{"Increase load","Pendlay row"}','{"Chest-supported row"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Inverted row','inverted-row','strength','{back,biceps,core}','{barbell,squat rack}','beginner','gym','{}',3,'6-12',NULL,75,'{"Set a bar at hip height and lie underneath it.","Grip just wider than shoulders, body in a straight line.","Pull your chest to the bar, squeezing shoulder blades.","Lower with control."}','{"Higher bar = easier. Adjust before form breaks.","Keep hips up — no sagging."}','{}','{"Seated row","Band row"}','{"Feet-elevated row","Weighted vest"}','{"Raise the bar height","Bent-knee row"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Pull-up','pull-up','strength','{back,biceps,core}','{pull-up bar}','advanced','gym','{}',4,'3-8',NULL,120,'{"Hang from the bar with hands just wider than shoulders.","Pull your chest toward the bar, driving elbows down.","Lower all the way under control."}','{"Avoid swinging or kipping unless coached.","Use a band or assisted machine to build up."}','{"Acute shoulder or elbow injury"}','{"Band-assisted pull-up","Lat pulldown","Inverted row"}','{"Weighted pull-up"}','{"Negative pull-up","Lat pulldown"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Overhead press','overhead-press','strength','{shoulders,triceps,core}','{barbell,dumbbell}','intermediate','gym','{}',3,'6-10',NULL,120,'{"Hold the weight at shoulder height, elbows under wrists.","Brace the core and glutes.","Press overhead until the arms lock out, head moves through slightly.","Lower to the shoulders."}','{"Do not lean back excessively — brace instead.","Stop if shoulder pain appears."}','{"Acute shoulder impingement","Uncontrolled hypertension"}','{"Landmine press","Seated dumbbell press"}','{"Increase load","Push press"}','{"Seated press","Band press"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Step-up','step-up','strength','{quadriceps,glutes}','{bench,box}','beginner','home','{}',3,'8-12 each leg',NULL,60,'{"Place one foot fully on a stable box at knee height or lower.","Drive through that heel to stand tall on the box.","Lower slowly under control."}','{"Do not push off the back foot to cheat the rep.","Use a lower box if the knee feels stressed."}','{"Balance impairment without support"}','{"Split squat","Reverse lunge"}','{"Higher box","Hold dumbbells"}','{"Lower box"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Farmer carry','farmer-carry','strength','{grip,core,traps}','{dumbbell,kettlebell}','beginner','gym','{}',3,NULL,40,60,'{"Pick up a heavy weight in each hand with a flat back.","Stand tall, shoulders down, core braced.","Walk with controlled steps for the set distance or time."}','{"Do not let the shoulders shrug or the torso lean.","Set the weights down with a hinge, not a round back."}','{"Acute back injury"}','{"Suitcase carry","Front rack carry"}','{"Heavier load","Longer distance"}','{"Lighter load","Shorter distance"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Brisk walking','brisk-walking','endurance','{cardiovascular,legs}','{none}','beginner','home','{}',NULL,NULL,1800,0,'{"Walk at a pace where you can talk but not sing.","Keep posture tall, arms swinging naturally.","Build duration before speed."}','{"Wear supportive shoes.","Start with 10-15 minutes if you are new to exercise."}','{}','{"Stationary cycling","Elliptical"}','{"Add incline","Increase pace or duration by ~10% per week"}','{"Shorter walks split through the day"}',NULL,'WHO physical activity guidelines','https://www.who.int/publications/i/item/9789240015128','high',true),
('Easy run','easy-run','endurance','{cardiovascular,legs}','{none}','beginner','home','{}',NULL,NULL,1500,0,'{"Run at a conversational pace.","Land under your hips with a relaxed cadence.","Finish feeling like you could keep going."}','{"Increase weekly volume by no more than about 10%.","Take walk breaks as needed — that is still training."}','{"Acute lower-limb injury","Stress fracture history without clearance"}','{"Walk-run intervals","Cycling","Rowing"}','{"Longer duration","Tempo run"}','{"Walk-run intervals"}',NULL,'WHO physical activity guidelines','https://www.who.int/publications/i/item/9789240015128','high',true),
('Interval run 4x4','interval-run-4x4','endurance','{cardiovascular,legs}','{none}','advanced','home','{}',4,NULL,240,180,'{"Warm up 10 minutes easy.","Run 4 minutes at a hard but sustainable effort (RPE 8).","Recover 3 minutes easy. Repeat 4 times.","Cool down 5-10 minutes."}','{"Only add intervals once you have a base of easy aerobic work.","Cap hard sessions at 2 per week for most people."}','{"Uncontrolled cardiovascular disease","Acute illness"}','{"Cycling intervals","Rowing intervals"}','{"Add a fifth interval"}','{"2 intervals","Reduce to 2 minutes hard"}',15,'Norwegian 4x4 protocol (Wisloff et al.)','https://pubmed.ncbi.nlm.nih.gov/17548726/','high',true),
('Stationary cycling','stationary-cycling','endurance','{cardiovascular,quadriceps}','{bike}','beginner','gym','{}',NULL,NULL,1800,0,'{"Set the saddle so the knee is slightly bent at the bottom.","Ride at a steady, conversational effort.","Keep cadence around 80-90 rpm."}','{"Saddle too low is the most common cause of knee pain.","Build duration gradually."}','{}','{"Brisk walking","Elliptical","Rowing"}','{"Add resistance","Add intervals"}','{"Shorter duration"}',NULL,'WHO physical activity guidelines','https://www.who.int/publications/i/item/9789240015128','high',true),
('Rowing machine steady','rowing-steady','endurance','{cardiovascular,back,legs}','{rower}','intermediate','gym','{}',NULL,NULL,1200,0,'{"Drive with the legs first, then lean back, then pull the arms.","Reverse the order on the recovery: arms, body, legs.","Keep a steady stroke rate around 20-24 spm."}','{"Do not round the lower back at the catch.","Legs do most of the work, not the arms."}','{"Acute lower-back pain"}','{"Cycling","Elliptical"}','{"Longer pieces","Intervals"}','{"Shorter pieces","Lower damper"}',NULL,'ACSM cardiorespiratory guidance','https://www.acsm.org','high',true),
('Jump rope','jump-rope','endurance','{cardiovascular,calves}','{jump rope}','intermediate','home','{}',5,NULL,60,45,'{"Jump just high enough to clear the rope, landing softly.","Turn the rope with the wrists, not the arms.","Stay tall with a braced core."}','{"Land quietly through the mid-foot to protect the shins.","Progress volume slowly to avoid calf and shin overload."}','{"Shin splints","Acute ankle or knee injury"}','{"Fast feet drill","Step-jacks"}','{"Double unders","Longer rounds"}','{"Rope-less jumping","Step-jacks"}',NULL,'ACSM cardiorespiratory guidance','https://www.acsm.org','high',true),
('Burpee','burpee','endurance','{full body}','{none}','advanced','home','{}',4,'8-12',NULL,60,'{"From standing, squat and place hands on the floor.","Jump or step feet back to a plank.","Perform a push-up (optional), then return feet under you.","Stand or jump up."}','{"Step back instead of jumping to reduce impact.","Stop when landing quality degrades."}','{"Acute wrist, knee or back injury","Uncontrolled hypertension"}','{"Squat thrust","Mountain climber"}','{"Add the push-up and jump"}','{"Step-back burpee without the jump"}',NULL,'ACSM movement guidelines','https://www.acsm.org','medium',true),
('Mountain climber','mountain-climber','endurance','{core,shoulders,hip flexors}','{none}','beginner','home','{}',4,NULL,30,30,'{"Start in a high plank.","Drive one knee toward the chest, then switch.","Keep the hips low and the pace controlled."}','{"Do not let the hips bounce up and down.","Slow down before form breaks."}','{"Acute wrist pain"}','{"Dead bug","Fast feet drill"}','{"Faster pace","Longer rounds"}','{"Slow step-in version"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Cat-cow','cat-cow','mobility','{spine,core}','{none}','beginner','home','{}',2,'8-10',NULL,30,'{"Start on hands and knees.","Inhale, drop the belly and lift the chest and tailbone.","Exhale, round the spine and tuck the chin.","Move slowly with the breath."}','{"Move within a comfortable range, never into pain.","Let the breath set the pace."}','{}','{"Seated spinal rotation","Child pose"}','{"Add segmental control"}','{"Seated version in a chair"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('World greatest stretch','worlds-greatest-stretch','mobility','{hips,thoracic spine,hamstrings}','{none}','intermediate','home','{}',2,'5 each side',NULL,30,'{"Step into a deep lunge.","Place the same-side hand inside the front foot.","Rotate the opposite arm up toward the ceiling.","Return and switch sides."}','{"Rotate from the upper back, not the lower back.","Keep the back knee soft."}','{"Acute hip or knee injury"}','{"Hip flexor stretch","Thoracic rotation"}','{"Add a hamstring sweep"}','{"Half-kneeling version"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('90/90 hip switch','90-90-hip-switch','mobility','{hips}','{none}','beginner','home','{}',3,'8 each side',NULL,30,'{"Sit with both knees bent at 90°, one in front and one out to the side.","Keep the chest tall.","Rotate the knees to switch sides without using your hands."}','{"Go only as far as your hips allow.","Stop if the knees feel pinched."}','{"Acute knee injury"}','{"Hip flexor stretch","Figure-four stretch"}','{"Hands-off switch","Add a hip lift"}','{"Use hands for support"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','medium',true),
('Thoracic rotation','thoracic-rotation','mobility','{thoracic spine,shoulders}','{none}','beginner','home','{}',2,'8 each side',NULL,30,'{"Kneel on all fours, one hand behind your head.","Rotate the elbow up toward the ceiling.","Return and rotate it under the body."}','{"Keep the lower back still — the movement comes from the upper back.","Move smoothly, no forcing."}','{}','{"Open book stretch","Seated spinal rotation"}','{"Add a band or a hold"}','{"Seated version"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('Ankle dorsiflexion drill','ankle-dorsiflexion-drill','mobility','{ankles,calves}','{none}','beginner','home','{}',2,'10 each side',NULL,30,'{"Half kneel with one foot flat, toes about a fist away from a wall.","Drive the knee forward over the toes without lifting the heel.","Return and repeat."}','{"The heel must stay down.","No pinching pain at the front of the ankle."}','{"Acute ankle sprain"}','{"Calf stretch","Downward dog"}','{"Increase the distance from the wall","Add load"}','{"Reduce the distance"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('Hamstring stretch','hamstring-stretch','flexibility','{hamstrings}','{none}','beginner','home','{}',2,NULL,30,20,'{"Sit or stand with one leg extended.","Hinge from the hips with a flat back until you feel a gentle stretch.","Hold and breathe."}','{"Stretch to mild tension, never pain.","Hold 20-30 seconds; do not bounce."}','{"Acute hamstring strain in the first days"}','{"Supine hamstring stretch with a strap"}','{"Longer holds","Loaded stretching"}','{"Bent-knee version"}',NULL,'ACSM flexibility guidance','https://www.acsm.org','high',true),
('Hip flexor stretch','hip-flexor-stretch','flexibility','{hip flexors,quadriceps}','{none}','beginner','home','{}',2,NULL,30,20,'{"Half kneel with the back knee padded.","Tuck the pelvis under and squeeze the back glute.","Shift slightly forward until you feel a stretch at the front of the hip."}','{"The stretch should be felt at the hip, not the lower back.","Keep the pelvis tucked."}','{"Acute knee pain in kneeling"}','{"Standing lunge stretch","Couch stretch"}','{"Add an overhead reach"}','{"Standing version"}',NULL,'ACSM flexibility guidance','https://www.acsm.org','high',true),
('Chest doorway stretch','chest-doorway-stretch','flexibility','{chest,shoulders}','{none}','beginner','home','{}',2,NULL,30,20,'{"Place your forearm on a doorframe with the elbow at shoulder height.","Step through gently until you feel a stretch across the chest.","Hold and breathe."}','{"Stop before any shoulder pinching.","Keep the ribs down."}','{"Shoulder instability"}','{"Floor angel","Band pull-apart"}','{"Vary the arm height"}','{"Lower the arm angle"}',NULL,'ACSM flexibility guidance','https://www.acsm.org','high',true),
('Child pose','child-pose','flexibility','{back,hips,shoulders}','{none}','beginner','home','{}',2,NULL,45,15,'{"Kneel and sit back toward your heels.","Reach the arms forward and let the chest sink.","Breathe slowly into the back of the ribs."}','{"Place a cushion under the hips if the knees complain."}','{"Acute knee injury"}','{"Seated forward fold"}','{"Side-reaching child pose"}','{"Cushion under the hips"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('Single-leg balance','single-leg-balance','balance','{ankles,glutes,core}','{none}','beginner','home','{}',3,NULL,30,30,'{"Stand on one leg with a soft knee.","Fix your eyes on a point ahead.","Hold, then switch legs."}','{"Stand near a wall for support when starting.","Progress by closing the eyes only when steady."}','{}','{"Tandem stance","Heel-to-toe walk"}','{"Eyes closed","Unstable surface","Add reaches"}','{"Fingertip support on a wall"}',NULL,'CDC falls-prevention balance guidance','https://www.cdc.gov/steadi/','high',true),
('Tandem walk','tandem-walk','balance','{ankles,core}','{none}','beginner','home','{}',3,'10 steps',NULL,30,'{"Walk heel-to-toe in a straight line.","Keep the eyes forward and arms out for balance."}','{"Use a wall or counter alongside you at first."}','{}','{"Single-leg balance"}','{"Eyes closed","Walk backwards"}','{"Hold a wall"}',NULL,'CDC falls-prevention balance guidance','https://www.cdc.gov/steadi/','high',true),
('Single-leg RDL','single-leg-rdl','balance','{hamstrings,glutes,core}','{none,dumbbell}','intermediate','home','{}',3,'6-10 each leg',NULL,60,'{"Stand on one leg, soft knee.","Hinge at the hip, reaching the other leg straight behind you.","Keep the hips square and the back flat.","Return to standing."}','{"Slow and controlled beats deep range.","Touch a wall for balance if needed."}','{"Acute hamstring strain"}','{"Romanian deadlift","Glute bridge"}','{"Hold a dumbbell","Deficit version"}','{"Kickstand RDL"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Pallof press','pallof-press','stability','{core,obliques}','{resistance band,cable}','beginner','gym','{}',3,'8-12 each side',NULL,45,'{"Stand side-on to a band anchored at chest height.","Hold the handle at your sternum.","Press straight out and resist the rotation.","Return slowly."}','{"The rep is about not rotating — keep the hips and shoulders square.","Breathe out on the press."}','{}','{"Plank","Dead bug"}','{"Step further from the anchor","Add a hold"}','{"Step closer to the anchor"}',NULL,'NSCA core stability guidance','https://www.nsca.com','high',true),
('Side plank','side-plank','stability','{obliques,glutes,shoulders}','{none}','intermediate','home','{}',3,NULL,25,45,'{"Lie on your side with the forearm under the shoulder.","Lift the hips so the body is a straight line.","Hold, then switch sides."}','{"Do not let the hips drop or rotate.","Bend the knees to reduce difficulty."}','{"Acute shoulder pain"}','{"Knee side plank","Pallof press"}','{"Top-leg raise","Add a reach-through"}','{"Knee side plank"}',NULL,'NSCA core stability guidance','https://www.nsca.com','high',true),
('Box jump','box-jump','power','{quadriceps,glutes,calves}','{box}','advanced','gym','{}',4,'3-5',NULL,120,'{"Stand a foot from a stable box.","Dip and swing the arms, then jump and land softly on the box.","Stand tall, then step down — do not jump down."}','{"Always step down to protect the achilles.","Use a low box first and stop when landings get sloppy.","Plyometrics need a strength base first."}','{"Acute lower-limb injury","No prior strength base","Growth-plate pain in young athletes"}','{"Squat jump","Broad jump"}','{"Higher box","Single-leg landings"}','{"Box step-up","Low box"}',14,'NSCA plyometric guidelines','https://www.nsca.com','high',true),
('Squat jump','squat-jump','power','{quadriceps,glutes,calves}','{none}','intermediate','home','{}',4,'4-6',NULL,90,'{"Dip into a quarter squat.","Jump as high as you can, arms swinging up.","Land softly through the mid-foot and reset each rep."}','{"Quality over quantity — stop when height drops.","Land quietly with bent knees."}','{"Acute knee or ankle injury","Growth-plate pain in young athletes"}','{"Box jump","Broad jump"}','{"Add a pause","Single-leg hop"}','{"Bodyweight squat with a fast stand"}',13,'NSCA plyometric guidelines','https://www.nsca.com','high',true),
('Broad jump','broad-jump','power','{glutes,hamstrings,quadriceps}','{none}','intermediate','home','{}',4,'3-5',NULL,120,'{"Stand with feet hip-width.","Swing the arms back, then jump forward as far as you can.","Land in a soft athletic stance and hold for a second."}','{"Stick the landing before adding distance.","Rest fully between reps — this is a power drill, not conditioning."}','{"Acute lower-limb injury"}','{"Squat jump","Box jump"}','{"Consecutive jumps"}','{"Sub-maximal jumps"}',13,'NSCA plyometric guidelines','https://www.nsca.com','high',true),
('Medicine ball slam','medicine-ball-slam','power','{core,shoulders,back}','{medicine ball}','intermediate','gym','{}',4,'6-8',NULL,90,'{"Hold the ball overhead with braced core.","Slam it into the floor using the whole body.","Pick it up and reset with a hinge."}','{"Use a non-bouncing slam ball.","Do not round the back when picking the ball up."}','{"Acute back or shoulder injury"}','{"Rotational throw","Kettlebell swing"}','{"Heavier ball","Rotational slam"}','{"Lighter ball"}',13,'NSCA power training guidance','https://www.nsca.com','high',true),
('Kettlebell swing','kettlebell-swing','power','{glutes,hamstrings,core}','{kettlebell}','intermediate','gym','{}',4,'10-15',NULL,90,'{"Hinge at the hips and hike the bell back between your legs.","Snap the hips forward to float the bell to chest height.","Let it swing back and repeat rhythmically."}','{"This is a hip hinge, not a squat or a front raise.","Keep the back flat and the arms relaxed."}','{"Acute lower-back injury"}','{"Romanian deadlift","Glute bridge"}','{"Heavier bell","Single-arm swing"}','{"Hip hinge drill","Lighter bell"}',14,'NSCA power training guidance','https://www.nsca.com','high',true),
('Sprint intervals 30m','sprint-30m','speed','{legs,cardiovascular}','{none}','advanced','home','{}',6,NULL,6,120,'{"Warm up thoroughly with drills and build-ups.","Sprint 30 m at near-maximal effort.","Walk back for full recovery and repeat."}','{"Never sprint cold — a full warm-up is non-negotiable.","Stop the session when times drop off noticeably.","Limit to 1-2 sprint sessions per week."}','{"Hamstring strain history without clearance","Acute lower-limb injury"}','{"Hill sprints","Flying 20s"}','{"More reps","Longer distance"}','{"Build-up runs at 70-80%"}',13,'NSCA speed training guidance','https://www.nsca.com','high',true),
('A-skip','a-skip','speed','{hip flexors,calves,coordination}','{none}','intermediate','home','{}',3,'20 m',NULL,60,'{"Skip forward driving one knee to hip height.","Land under the hips on the ball of the foot.","Keep the arms driving in rhythm."}','{"Stay tall — do not lean back.","Rhythm before speed."}','{}','{"High knees","B-skip"}','{"B-skip","Faster tempo"}','{"March version"}',NULL,'NSCA speed training guidance','https://www.nsca.com','high',true),
('Lateral shuffle','lateral-shuffle','speed','{glutes,adductors,calves}','{cones}','beginner','home','{football,basketball,tennis,badminton,volleyball}',4,'20 s',NULL,60,'{"Get into an athletic stance, hips low.","Shuffle sideways without crossing the feet.","Stay low and change direction on a cue."}','{"Keep the chest up and hips down.","Do not click the heels together."}','{"Acute groin strain"}','{"Carioca","Cone weave"}','{"Add a reactive cue","Longer distance"}','{"Slower tempo"}',NULL,'NSCA agility guidance','https://www.nsca.com','high',true),
('T-drill agility','t-drill','speed','{legs,cardiovascular}','{cones}','intermediate','gym','{football,basketball,tennis,cricket}',4,NULL,15,90,'{"Set cones in a T shape.","Sprint forward, shuffle left, shuffle right, shuffle back to the middle, then backpedal to start.","Rest fully between reps."}','{"Decelerate with a wide base to protect the knees.","Full recovery between reps keeps the quality high."}','{"Acute knee or ankle injury"}','{"5-10-5 shuttle","Lateral shuffle"}','{"Add a reactive start"}','{"Reduce distances"}',13,'NSCA agility guidance','https://www.nsca.com','high',true),
('Nordic hamstring curl','nordic-hamstring-curl','strength','{hamstrings}','{partner,bench}','advanced','gym','{football,athletics,cricket}',3,'4-6',NULL,120,'{"Kneel with the ankles anchored.","Lower your torso forward as slowly as you can control.","Catch with the hands and push back to the start."}','{"Expect soreness — start with 1-2 sets and build very slowly.","Control the lowering; do not free-fall."}','{"Acute hamstring strain"}','{"Romanian deadlift","Glute-ham raise"}','{"Slower eccentric","More reps"}','{"Band-assisted nordic","Higher catch point"}',15,'FIFA 11+ / hamstring injury prevention evidence','https://pubmed.ncbi.nlm.nih.gov/26746908/','high',true),
('Copenhagen adduction','copenhagen-adduction','strength','{adductors,core}','{bench}','advanced','gym','{football,hockey,basketball}',3,'6-10 each side',NULL,90,'{"Side plank with the top leg resting on a bench.","Lift the bottom leg to meet the bench.","Lower under control."}','{"Start with the short-lever (knee on bench) version.","Groin soreness is common — progress slowly."}','{"Acute groin strain"}','{"Adductor squeeze","Side plank"}','{"Long-lever version","More reps"}','{"Short-lever version","Adductor squeeze isometric"}',15,'Groin injury prevention evidence (Harøy et al.)','https://pubmed.ncbi.nlm.nih.gov/30498004/','high',true),
('Calf raise','calf-raise','strength','{calves}','{none}','beginner','home','{}',3,'12-20',NULL,60,'{"Stand tall, rise onto the balls of the feet.","Pause at the top.","Lower slowly to a full stretch."}','{"Hold a wall for balance.","Slow lowering is where most of the benefit is."}','{"Acute achilles pain"}','{"Seated calf raise","Single-leg calf raise"}','{"Single-leg","Add load","Deficit"}','{"Both legs","Reduced range"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Face pull','face-pull','strength','{rear delts,upper back}','{resistance band,cable}','beginner','gym','{}',3,'12-15',NULL,60,'{"Set a band or cable at face height.","Pull toward your forehead, elbows high, hands apart.","Squeeze the shoulder blades and return slowly."}','{"Light loads and high reps work best here.","Keep the neck relaxed."}','{}','{"Band pull-apart","Reverse fly"}','{"Add a hold","More load"}','{"Band pull-apart"}',NULL,'NSCA resistance training guidance','https://www.nsca.com','high',true),
('Band pull-apart','band-pull-apart','mobility','{upper back,rear delts}','{resistance band}','beginner','home','{}',3,'12-20',NULL,45,'{"Hold a band at shoulder width, arms straight out in front.","Pull the band apart until the arms are wide.","Return slowly."}','{"Keep the ribs down and the shoulders away from the ears."}','{}','{"Face pull","Floor angel"}','{"Thicker band","Slower tempo"}','{"Wider grip","Lighter band"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('Wall sit','wall-sit','strength','{quadriceps,glutes}','{none}','beginner','home','{}',3,NULL,30,45,'{"Slide down a wall until the knees are about 90°.","Keep the back flat against the wall.","Hold and breathe."}','{"Raise the position if the knees complain.","Do not hold your breath."}','{"Acute knee pain","Uncontrolled hypertension (isometrics raise blood pressure)"}','{"Bodyweight squat","Leg extension"}','{"Longer holds","Single-leg wall sit"}','{"Higher position","Shorter holds"}',NULL,'ACSM movement guidelines','https://www.acsm.org','high',true),
('Superman hold','superman-hold','stability','{lower back,glutes}','{none}','beginner','home','{}',3,NULL,20,40,'{"Lie face down, arms extended forward.","Lift the chest, arms and legs a few inches.","Hold, then lower with control."}','{"Small lift is enough — do not crank the lower back.","Keep the neck neutral."}','{"Acute lower-back pain that worsens with extension"}','{"Bird dog","Glute bridge"}','{"Longer holds","Alternating limbs"}','{"Arms-only or legs-only"}',NULL,'NSCA core stability guidance','https://www.nsca.com','high',true),
('Foam rolling quads','foam-roll-quads','recovery','{quadriceps}','{foam roller}','beginner','home','{}',1,NULL,60,0,'{"Lie face down with a roller under the thighs.","Roll slowly from the hip to just above the knee.","Pause on tender spots and breathe."}','{"Avoid rolling directly over joints or bone.","Discomfort is fine; sharp pain is not."}','{"Acute muscle tear","Blood clot risk","Skin infection in the area"}','{"Static stretching","Gentle walking"}','{"Longer duration"}','{"Lighter pressure"}',NULL,'Foam rolling recovery evidence (Wiewelhove et al.)','https://pubmed.ncbi.nlm.nih.gov/31024339/','medium',true),
('Box breathing','box-breathing','recovery','{nervous system}','{none}','beginner','home','{}',1,NULL,300,0,'{"Inhale through the nose for 4 seconds.","Hold for 4 seconds.","Exhale for 4 seconds. Hold for 4 seconds.","Repeat for 3-5 minutes."}','{"If 4 seconds feels long, use 3.","Stop if you feel lightheaded."}','{}','{"Diaphragmatic breathing","Gentle walk"}','{"Longer counts"}','{"Shorter counts"}',NULL,'Autonomic recovery / slow breathing evidence','https://pubmed.ncbi.nlm.nih.gov/29616846/','medium',true),
('Easy recovery walk','recovery-walk','recovery','{cardiovascular}','{none}','beginner','home','{}',1,NULL,1200,0,'{"Walk at an easy, relaxed pace.","Breathe through the nose if comfortable.","Keep it short and gentle — this is not a training session."}','{"If you feel worse afterwards, take full rest instead."}','{}','{"Light cycling","Mobility flow"}','{"Slightly longer"}','{"Full rest day"}',NULL,'WHO physical activity guidelines','https://www.who.int/publications/i/item/9789240015128','high',true),
('Mobility flow 10 min','mobility-flow-10','mobility','{full body}','{none}','beginner','home','{}',1,NULL,600,0,'{"Cycle through cat-cow, world greatest stretch, 90/90 hip switch and thoracic rotation.","Spend about 2 minutes on each, moving with the breath."}','{"Move within a pain-free range.","Slow beats deep."}','{}','{"Individual mobility drills"}','{"Longer flow","Add loaded stretching"}','{"5-minute version"}',NULL,'General mobility guidance','https://www.nhs.uk/live-well/exercise/','high',true),
('Dynamic warm-up','dynamic-warm-up','mobility','{full body}','{none}','beginner','home','{}',1,NULL,480,0,'{"2 minutes easy cardio (march, jog or skip).","Leg swings, hip circles and arm circles.","World greatest stretch and A-skips.","2-3 build-up efforts of the movement you are about to train."}','{"Warm up before every session, especially before sprinting or lifting heavy.","Dynamic before training, static stretching after."}','{}','{"Sport-specific warm-up","FIFA 11+"}','{"Add sport drills"}','{"5-minute version"}',NULL,'ACSM warm-up guidance','https://www.acsm.org','high',true),
('Cone dribble drill','cone-dribble','speed','{legs,coordination}','{cones,ball}','beginner','home','{football,hockey,basketball}',4,NULL,45,60,'{"Set 5-6 cones about a metre apart.","Dribble through them with small controlled touches.","Turn and repeat, increasing pace as control allows."}','{"Control first, speed second.","Use both feet or both hands."}','{}','{"Lateral shuffle","T-drill"}','{"Tighter spacing","Head-up dribbling"}','{"Wider spacing","Walking pace"}',NULL,'General sport conditioning guidance','https://www.nsca.com','medium',true),
('Shoulder external rotation','shoulder-external-rotation','stability','{rotator cuff}','{resistance band}','beginner','home','{cricket,swimming,tennis,badminton,volleyball}',3,'12-15 each side',NULL,45,'{"Hold a band with the elbow tucked at 90°.","Rotate the forearm outward, keeping the elbow at your side.","Return slowly."}','{"Light resistance only — this is a control exercise.","Elbow stays pinned to the ribs."}','{"Acute shoulder pain"}','{"Side-lying external rotation"}','{"Thicker band","Add a hold"}','{"Lighter band","Shorter range"}',NULL,'Overhead athlete shoulder care guidance','https://www.nsca.com','high',true),
('Swim easy laps','swim-easy','endurance','{full body,cardiovascular}','{pool}','beginner','gym','{swimming,triathlon}',NULL,NULL,1200,0,'{"Swim at a relaxed pace with steady breathing.","Focus on a long stroke and steady rhythm.","Rest at the wall as needed."}','{"Never swim alone in open water.","Stop if you feel breathless or cold."}','{"Ear infection","Open wounds"}','{"Aqua jogging","Cycling"}','{"Longer sets","Interval sets"}','{"Shorter sets with rest"}',NULL,'WHO physical activity guidelines','https://www.who.int/publications/i/item/9789240015128','high',true),
('Hill sprint','hill-sprint','speed','{glutes,hamstrings,calves}','{none}','advanced','home','{football,athletics,rugby}',6,NULL,10,150,'{"Find a moderate hill.","Sprint hard uphill for 8-12 seconds.","Walk down for full recovery and repeat."}','{"Hills reduce hamstring strain risk compared with flat sprints, but still warm up fully.","Stop when speed drops off."}','{"Acute lower-limb injury"}','{"Flat sprints","Bike sprints"}','{"More reps","Steeper hill"}','{"Sub-maximal hill strides"}',13,'NSCA speed training guidance','https://www.nsca.com','high',true),
('Bike sprint intervals','bike-sprints','endurance','{legs,cardiovascular}','{bike}','intermediate','gym','{cycling,football,athletics}',8,NULL,20,100,'{"Warm up 10 minutes easy.","Sprint hard for 20 seconds against moderate resistance.","Spin easy for 100 seconds. Repeat."}','{"Low impact, so it suits people managing joint load.","Keep hard sessions to 1-2 per week."}','{"Uncontrolled cardiovascular disease"}','{"Rowing intervals","Hill sprints"}','{"More reps","Longer efforts"}','{"Fewer reps","Lower resistance"}',13,'ACSM cardiorespiratory guidance','https://www.acsm.org','high',true),
('Posture reset drill','posture-reset','mobility','{upper back,neck,shoulders}','{none}','beginner','home','{}',3,'8-10',NULL,30,'{"Stand with the back against a wall, heels a few inches out.","Flatten the lower back gently and tuck the chin.","Slide the arms up and down the wall like a snow angel."}','{"Keep the wrists and elbows touching the wall as far as comfortable.","Do this through long study or desk days."}','{}','{"Band pull-apart","Thoracic rotation"}','{"Longer holds","Add a band"}','{"Reduced arm range"}',NULL,'General posture and mobility guidance','https://www.nhs.uk/live-well/exercise/','medium',true);